# From https://github.com/JohnLithio/AUDL-Advanced-Stats/blob/main/audl_advanced_stats/constants.py
EVENT_TYPES = {
    1: "Start of O-Point",
    2: "Start of D-Point",
    3: "In-bounds Pull",
    4: "Out-of-bounds Pull",
    5: "Block",
    6: "Callahan",
    7: "Opponent Callahan",
    8: "Throwaway",
    9: "Throwaway Caused",
    10: "Travel",
    11: "Opponent Travel",
    12: "Opponent Foul",
    13: "Own Foul",
    14: "Timeout",
    15: "Opponent Timeout",
    # 16: "",
    17: "Stall",
    18: "Opponent Stall",
    19: "Drop",
    20: "Completion",
    21: "Opponent Score",
    22: "Score",
    23: "End of 1st Quarter",
    24: "End of 2nd Quarter",
    25: "End of 3rd Quarter",
    26: "End of 4th Quarter",
    27: "End of 1st Overtime",
    28: "End of 2nd Overtime",
    # 29: "",
    # 30: "",
    # 31: "",
    # 32: "",
    # 33: "",
    # 34: "",
    # 35: "",
    # 36: "",
    # 37: "",
    # 38: "",
    # 39: "",
    40: "Substitutions",
    41: "Substitutions",
    42: "Opponent Injury",
    43: "Injury",
    44: "Offsides",
    45: "Opponent Offsides",
    # 46: "",
}

EVENT_TYPES_GENERAL = {
    3: "Pull",
    4: "Pull",
    5: "Turnover",
    6: "Score",
    7: "Turnover",
    8: "Turnover",
    9: "Turnover",
    17: "Turnover",
    18: "Turnover",
    19: "Turnover",
    21: "Score",
    22: "Score",
    23: "End of Period",
    24: "End of Period",
    25: "End of Period",
    26: "End of Period",
    27: "End of Period",
}
