version: '3'
services:
  web:
    container_name: my app
    build: .
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      DEBUG: 1
    ports:
      - "80:80"
    restart: on-failure