version: '3'
services:
  web:
    container_name: myapp
    build: 
      context: ./code/
      dockerfile: ./Dockerfile
    volumes:
      - ./code:/code
    command: gunicorn -b :8000 -k uvicorn.workers.UvicornWorker app.main:app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
      restart: on-failure