version: '2'
services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PW
      MYSQL_DATABASE: test
      MYSQL_USER: audl-api
      MYSQL_PASSWORD: $AUDL_API_PW
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - db